// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwVL7nNVHdRJS_su2yigP8RKO9-6_8ZXo',
    appId: '1:714787563695:web:c104dd6a23ff744edb4c5a',
    messagingSenderId: '714787563695',
    projectId: 'travelappflutterfinal',
    authDomain: 'travelappflutterfinal.firebaseapp.com',
    storageBucket: 'travelappflutterfinal.firebasestorage.app',
    measurementId: 'G-SC8LWEDC49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABEwUXyidurcRrV8SbprVgXkKU8X21hn8',
    appId: '1:714787563695:android:4d811c11596900bedb4c5a',
    messagingSenderId: '714787563695',
    projectId: 'travelappflutterfinal',
    storageBucket: 'travelappflutterfinal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1QuJIOpIsR63RDExNDzxVAHxj6_2EFuY',
    appId: '1:714787563695:ios:0c628acc512e574cdb4c5a',
    messagingSenderId: '714787563695',
    projectId: 'travelappflutterfinal',
    storageBucket: 'travelappflutterfinal.firebasestorage.app',
    iosBundleId: 'com.example.travelapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1QuJIOpIsR63RDExNDzxVAHxj6_2EFuY',
    appId: '1:714787563695:ios:0c628acc512e574cdb4c5a',
    messagingSenderId: '714787563695',
    projectId: 'travelappflutterfinal',
    storageBucket: 'travelappflutterfinal.firebasestorage.app',
    iosBundleId: 'com.example.travelapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwVL7nNVHdRJS_su2yigP8RKO9-6_8ZXo',
    appId: '1:714787563695:web:1a6c7c01af835e9cdb4c5a',
    messagingSenderId: '714787563695',
    projectId: 'travelappflutterfinal',
    authDomain: 'travelappflutterfinal.firebaseapp.com',
    storageBucket: 'travelappflutterfinal.firebasestorage.app',
    measurementId: 'G-G0RFCSHQQT',
  );
}
